name: "Build the extension"
on:
  pull_request:
    # Only the following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Build the extension
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096 --trace-warnings"
          echo "Building extension without zip first..."
          pnpm build
          echo "Build completed, now creating zip..."
          cd build && zip -r chrome-mv3-prod.zip chrome-mv3-prod/
        env:
          NODE_ENV: production

      - name: Archive the extension production build as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-prod-build
          path: build/chrome-mv3-prod.zip
          retention-days: 30
