name: "Build the extension"
on:
  pull_request:
    # Only the following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Build the extension
        # Note: I added the sharp package because the GitHub CI was failing due to the missing sharp package?!?
        run: pnpm install sharp && pnpm build --zip
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          npm_config_platform: "linux"
          npm_config_arch: "x64"

      - name: Archive the extension production build as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-prod-build
          path: build/chrome-mv3-prod.zip
          retention-days: 30
